### PR TITLE
Added Schema, ERD, Classes and Objects

### PR DESCRIPTION
**Pull request by AnjaniKumar1515**
In this PR the changes I have implemented are as follows:-
# DBMS
- Included ER Diagram 
- Included Schema Diagram
- Link to the walkthrough video: - https://www.loom.com/share/0dfbb12712fc4078912a504fde466a81?sid=da8b92de-9f67-4448-acca-7108939fb388

# OOPs
-Implemented Classes 
- Implemented setter and getter functions for each class
- Created an instance of each class (object)
- Displayed the object by running the code and retrieved data from the object. 
-  Link to the walkthrough video: - https://www.loom.com/share/c47cd960b90b4c7ea3fd929ced1567e5?sid=694fe3e4-03e6-4570-b524-9afac7956b75

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Idea explanation is good,
But the ERD and Schema are not matched with each other, 
Schema is good and has every proper entities and connections, 
but ERD is missing some entities (pet_food, pet_activity) with attributes and their appropriate connections with pet entity.

**Comment by AnjaniKumar1515** [comment]
I have updated the ER Diagram and added the missing Entities. Thanks for pointing that out. I have commited the update. You can review it as well and let me know.

**Review by th3c0d3br34ker — APPROVED** [review]
thanks @AnjaniKumar1515 , i reviewed your loom. your have explained the concept well. the idea is also very interesting.

please go ahead and merge it. [for OOP review]

**Comment by PRASANNAPATHI** [comment]
Yes anjaniKumar, your ERD is fine now, just add the cardinality relationships (such as 1 to N).

You can merge it [for DBMS].

**Pull request merged**
