### PR TITLE
Milestone 2 covered for OOPs and DBMS. 

### PR DESCRIPTION
**Pull request by AnjaniKumar1515**
In this PR I have made the following changes:-

# DBMS 
- Created the relational data model using tables and insured normalization (1NF, 2NF, 3NF)
- Added the tables, pets, skills, users, user-pets, pet-skills etc.
- Used DDL commands to create, alter and drop tables from the database. 
- Here is the link to the two videos explaining the concepts. 
- https://www.loom.com/share/4041a2f6e55d404690458d67b061dd49?sid=0c6c381d-72ca-4743-821b-192643571c7a
- https://www.loom.com/share/cd5feb61f65348b0b63c1a738fa5e489?sid=b53e98aa-1a2c-4c71-9181-c867c4e2cfb1
- https://www.loom.com/share/7069c330ac7f478f90fde8b9c44a104d?sid=d66e649f-abd7-44a9-bea0-a3a7ae60b29a
- https://www.loom.com/share/4bee44ba2b83496b85424b2adc1e33fb?sid=ccde83ab-7522-41ac-a579-4de0e56ae32b

# OOPS 

- Added rest of classes 
- Used constructors to create objects, destructors to delete them
- Used this pointers to create different methods to feed, teach and play with pets. 
- Here is the video of me explaining the concepts:-
- https://www.loom.com/share/b95f404050f34c5f9a21920facb3dc06?sid=26c57410-6592-49e2-85a2-2e6eeceb1f8a

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hey @AnjaniKumar1515 , thanks for submitting for DBMS.
It seems, your self viva video is not sufficient for DDL & Normalization. Please consider the following,

For DDL- 
Create- please explain each tables with each attributes in detail, along with their keys and constraints. Execute all tables in database at end.
Alter- please execute the command working and show the changes
Drop- same as Alter, execute and show the changes.

For Normalization-
1 NF is not only about having only one primary key, its also about having only single valued attributes in each columns, So you should show and explain those things.
2 NF, 3NF - you just explained that you made sure it follows these, But you should show each part and explain, how it is implemented and applied.

Please make video with these corrections.

**Comment by AnjaniKumar1515** [comment]
Hey, @PRASANNAPATHI, I have made another video, and added it, can you please check  it out. i have added the video to the PR description. 
Hey @PRASANNAPATHI, I have updated the video on normalization in the PR description. Please check it out. Thanks!

**Comment by PRASANNAPATHI** [comment]
Yes @AnjaniKumar1515 , for DDL, Its fine now.

You can merge it for DDL.

About normalization - expecting an updated video.

**Review by th3c0d3br34ker — APPROVED** [review]
thanks @AnjaniKumar1515 for your submission. the self-viva is satisfactory for `Constructors & Destructors` and `this` pointer. 

please go ahead an merge this PR. [for OOP]

**Comment by PRASANNAPATHI** [comment]
Hey @AnjaniKumar1515 , 
Normalization is fine now.

Please merge it.

**Pull request merged**
