### PR TITLE
Milestone 4 of OOPs and DBMS project Virtual Pet Simulator

### PR DESCRIPTION
**Pull request by AnjaniKumar1515**
# OOPs
- Used Dynamic Memory Allocation 
- Used smart pointers instead of new and delete 
- Made sub classes and virtual function to showcase abstraction 
- Defined incapsulation 
- The explanation videos are as follows 
- https://www.loom.com/share/7882588cc55e4e58bcc353d4c1d2afe9?sid=cf3ff688-e6cc-4850-b47d-c79660fa495c
- https://www.loom.com/share/e8fed2ba71394228ab36ab16285cb33c?sid=277ac544-ac8c-49b3-a720-73d5738574e3
- https://www.loom.com/share/9121a33216fd43d3b84291891ee74176?sid=c56f55b1-902b-4c74-b30a-11773280d128

# DBMS 
- Implemented Subqueries
- Used join and subqueries to display pets on skills they have learnt
- Used subqueries to show which pet can eat which specific food 
- Used join and subqueries to display which pet has learnt which skill 
- The explanation videos are as follows:-
- Added sorting of users based on highest level of happiness of pet 
- Finding pets which have eaten more food than the average.
- https://www.loom.com/share/c2bb59cf33a7434187672f192b1340c5?sid=3066fb1e-a837-4057-900a-3bedd303f359
- https://www.loom.com/share/fa5fef45f7b14046a853a30e58634420?sid=07b50617-ceaa-4104-8003-6e81fb773269

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hey @AnjaniKumar1515 ,

Your explanation and queries are really good.

But, the only missing thing is subquery, you have implemented all your queries using join.

Please, you can merge it now.

If you want to score fully, then just please add one more query where you apply subquery.

**Comment by AnjaniKumar1515** [comment]
> Hey @AnjaniKumar1515 ,
> 
> Your explanation and queries are really good.
> 
> But, the only missing thing is subquery, you have implemented all your queries using join.
> 
> Please, you can merge it now.
> 
> If you want to score fully, then just please add one more query where you apply subquery.

I will add it within a few minutes and commit it, I will let you know once it is done!

**Comment by AnjaniKumar1515** [comment]
@PRASANNAPATHI, I have added two more subqueries and committed them. One is to find users based on highest level of happiness of pet and the other is to find the pets that have consumed more food than the rest.

**Comment by PRASANNAPATHI** [comment]
Yes @AnjaniKumar1515 ,
Everything is fine now.

Please merge it now for Advanced SQL Queries (DBMS).

And resubmit the same link in livebooks to update the scores.

**Comment by AnjaniKumar1515** [comment]
> Yes @AnjaniKumar1515 , Everything is fine now.
> 
> Please merge it now for Advanced SQL Queries (DBMS).
> 
> And resubmit the same link in livebooks to update the scores.

@PRASANNAPATHI, I have updated the link in the livebooks. Can you please check. Thanks!

**Comment by th3c0d3br34ker** [comment]
thanks @AnjaniKumar1515 for your submission. please go ahead and merge this PR for `Dynamic memory allocation` and `Encapsulation & Abstraction`

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
